[package]
name = "sgleam"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.1.9"
clap = { version = "4", features = ["derive"] }
dirs = "5"
gleam-core = { git = "https://github.com/gleam-lang/gleam.git", tag = "v1.5.0" }
im = "15.1.0"
rquickjs = { git = "https://github.com/malbarbo/rquickjs", branch = "fix-gleam-stdlib", features = ["loader"] }
rustyline = "14"
tar = "0.4.41"
termcolor = "1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
